export const hexagramInfo = [
    { number: 1, name: 'The Creative', binary: '111111', symbol: '☰☰' },
    { number: 2, name: 'The Receptive', binary: '000000', symbol: '☷☷' },
    { number: 3, name: 'Difficulty at the Beginning', binary: '100010', symbol: '☳☴' },
    { number: 4, name: 'Youthful Folly', binary: '010001', symbol: '☵☶' },
    { number: 5, name: 'Waiting (Nourishment)', binary: '111010', symbol: '☰☱' },
    { number: 6, name: 'Conflict', binary: '010111', symbol: '☱☰' },
    { number: 7, name: 'The Army', binary: '010000', symbol: '☵☷' },
    { number: 8, name: 'Holding Together (Union)', binary: '000010', symbol: '☷☱' },
    { number: 9, name: 'The Taming Power of the Small', binary: '111011', symbol: '☰☲' },
    { number: 10, name: 'Treading (Conduct)', binary: '110111', symbol: '☱☰' },
    { number: 11, name: 'Peace', binary: '111000', symbol: '☰☷' },
    { number: 12, name: 'Standstill (Stagnation)', binary: '000111', symbol: '☷☰' },
    { number: 13, name: 'Fellowship with Men', binary: '101111', symbol: '☰☲' },
    { number: 14, name: 'Possession in Great Measure', binary: '111101', symbol: '☲☰' },
    { number: 15, name: 'Modesty', binary: '001000', symbol: '☶☷' },
    { number: 16, name: 'Enthusiasm', binary: '000100', symbol: '☷☳' },
    { number: 17, name: 'Following', binary: '100110', symbol: '☳☱' },
    { number: 18, name: 'Work on What Has Been Spoiled', binary: '011001', symbol: '☶☵' },
    { number: 19, name: 'Approach', binary: '110000', symbol: '☱☷' },
    { number: 20, name: 'Contemplation (View)', binary: '000011', symbol: '☷☲' },
    { number: 21, name: 'Biting Through', binary: '100101', symbol: '☳☲' },
    { number: 22, name: 'Grace', binary: '101001', symbol: '☲☶' },
    { number: 23, name: 'Splitting Apart', binary: '000001', symbol: '☷☶' },
    { number: 24, name: 'Return (The Turning Point)', binary: '100000', symbol: '☳☷' },
    { number: 25, name: 'Innocence (The Unexpected)', binary: '100111', symbol: '☳☰' },
    { number: 26, name: 'The Taming Power of the Great', binary: '111001', symbol: '☰☶' },
    { number: 27, name: 'The Corners of the Mouth', binary: '100001', symbol: '☳☶' },
    { number: 28, name: 'Preponderance of the Great', binary: '011111', symbol: '☱☰' },
    { number: 29, name: 'The Abysmal (Water)', binary: '101000', symbol: '☲☷' },
    { number: 30, name: 'The Clinging (Fire)', binary: '000101', symbol: '☷☲' },
    { number: 31, name: 'Influence (Wooing)', binary: '001111', symbol: '☱☰' },
    { number: 32, name: 'Duration', binary: '111100', symbol: '☰☳' },
    { number: 33, name: 'Retreat', binary: '000110', symbol: '☷☱' },
    { number: 34, name: 'The Power of the Great', binary: '011000', symbol: '☱☷' },
    { number: 35, name: 'Progress', binary: '010100', symbol: '☱☳' },
    { number: 36, name: 'Darkening of the Light', binary: '001010', symbol: '☶☱' },
    { number: 37, name: 'The Family', binary: '101101', symbol: '☲☲' },
    { number: 38, name: 'Opposition', binary: '001011', symbol: '☶☲' },
    { number: 39, name: 'Obstruction', binary: '111110', symbol: '☰☱' },
    { number: 40, name: 'Deliverance', binary: '011111', symbol: '☱☰' },
    { number: 41, name: 'Decrease', binary: '000111', symbol: '☷☰' },
    { number: 42, name: 'Increase', binary: '111000', symbol: '☰☷' },
    { number: 43, name: 'Break-through (Resoluteness)', binary: '111011', symbol: '☰☲' },
    { number: 44, name: 'Coming to Meet', binary: '110111', symbol: '☱☰' },
    { number: 45, name: 'Gathering Together (Massing)', binary: '101010', symbol: '☲☱' },
    { number: 46, name: 'Pushing Upward', binary: '010101', symbol: '☱☲' },
    { number: 47, name: 'Oppression (Exhaustion)', binary: '100100', symbol: '☳☳' },
    { number: 48, name: 'The Well', binary: '001001', symbol: '☶☶' },
    { number: 49, name: 'Revolution (Molting)', binary: '110101', symbol: '☱☲' },
    { number: 50, name: 'The Cauldron', binary: '101011', symbol: '☲☲' },
    { number: 51, name: 'The Arousing (Shock)', binary: '010110', symbol: '☱☱' },
    { number: 52, name: 'Keeping Still (Mountain)', binary: '011010', symbol: '☱☱' },
    { number: 53, name: 'Development (Gradual Progress)', binary: '101100', symbol: '☲☳' },
    { number: 54, name: 'The Marrying Maiden', binary: '001101', symbol: '☶☲' },
    { number: 55, name: 'Abundance (Fullness)', binary: '011011', symbol: '☱☲' },
    { number: 56, name: 'The Wanderer', binary: '110110', symbol: '☱☱' },
    { number: 57, name: 'The Gentle (Wind)', binary: '001100', symbol: '☶☳' },
    { number: 58, name: 'The Joyous (Lake)', binary: '000110', symbol: '☷☱' },
    { number: 59, name: 'Dispersion (Dissolution)', binary: '011100', symbol: '☱☳' },
    { number: 60, name: 'Limitation', binary: '001110', symbol: '☶☱' },
    { number: 61, name: 'Inner Truth', binary: '110100', symbol: '☱☳' },
    { number: 62, name: 'Preponderance of the Small', binary: '001011', symbol: '☶☲' },
    { number: 63, name: 'After Completion', binary: '100011', symbol: '☳☲' },
    { number: 64, name: 'Before Completion', binary: '110001', symbol: '☱☶' }
  ];
  